### ISSUE TITLE
Add more test FMUs

### ISSUE THREAD

**Issue by AnHeuermann** [AnHeuermann/JuliaFMI#11]
Provide helloWorld and BouncingBall FMUs from multiple different tools.
Maybe Dymola, Matlab, SimulationX, ...

**Comment by AnHeuermann** [comment]
Test with FMUs from https://github.com/modelica/fmi-cross-check

**Comment by cuihantao** [comment]
Do you have the download link for HelloWorld and BouncingBall for all platforms? I tried to find them from fmi-cross-check, and I only found BouncingBall.fmu from testFMU.

I want to add compatibility for macOS (darwin64). Currently I've compiled logger.c and modified a few lines. Next I'm looking to run the tests.

**Comment by AnHeuermann** [comment]
I created the FMUs from Modelica models with [OpenModelica]( https://openmodelica.org/download/download-mac). It's Open-Source and should work on macOS.
Just save these .mo files, load in OpenModelcia and export as FMI. I can't do it myselfe since I don't have a Mac.

HelloWorld.mo
```
model HelloWorld
  Real x(start=1);
  parameter Real a=2;
equation
  der(x) = a * x;
end HelloWorld;
```

BouncingBall.mo
```
model BouncingBall
  parameter Real e=0.7 "coefficient of restitution";
  parameter Real g=9.81 "gravity acceleration";
  Real h(start=1) "height of ball";
  Real v "velocity of ball";
  Real v_new;
equation
  der(v) = -g;
  der(h) = v;
  when h <= 0.0 then
    v_new = -e*pre(v);
    reinit(v, v_new);
  end when;
end BouncingBall;
```

**Comment by cuihantao** [comment]
Thanks! Working on it. Will send a PR once all tests pass.
